import JSZip from 'jszip';

export interface ProjectPackageOptions {
  projectName: string;
  learnerName: string;
  html: string;
  css: string;
  js: string;
}

/**
 * Generates clean standalone HTML boilerplate linking style.css and script.js
 */
export function buildStandaloneHtml(
  projectName: string,
  learnerName: string,
  bodyHtml: string
): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${projectName} — Built by ${learnerName}</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
${bodyHtml}

  <script src="script.js"></script>
</body>
</html>`;
}

/**
 * Packages project files into a downloadable ZIP archive using JSZip
 */
export async function generateProjectZip(
  options: ProjectPackageOptions
): Promise<{ blob: Blob; filename: string; file: File }> {
  const zip = new JSZip();
  const slug = options.projectName.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '') || 'web-project';
  const folderName = `${slug}-by-${options.learnerName.toLowerCase().replace(/[^a-z0-9]+/g, '') || 'learner'}`;
  const root = zip.folder(folderName) || zip;

  // 1. index.html
  const completeHtml = buildStandaloneHtml(
    options.projectName,
    options.learnerName,
    options.html
  );
  root.file('index.html', completeHtml);

  // 2. style.css
  root.file('style.css', options.css || '/* Internet Mission Custom Styles */\n');

  // 3. script.js
  root.file('script.js', options.js || '// Internet Mission Custom Script\nconsole.log("Website Loaded!");\n');

  // 4. README.md
  const readmeContent = `# ${options.projectName}

Built with pride by **${options.learnerName}** on [Internet Mission](https://internet-mission.app).

## 🚀 Overview
This website was built using pure semantic HTML, modern CSS, and JavaScript.

## 📂 Project Structure
- \`index.html\` - Semantic webpage markup
- \`style.css\` - Custom styling, layout & responsive colors
- \`script.js\` - Dynamic client-side interactivity
- \`assets/\` - Project media and resources

## 💻 How to Run
Double-click \`index.html\` in any web browser to open the website locally!

---
*Generated by Internet Mission — Learn. Build. Level Up.*
`;
  root.file('README.md', readmeContent);

  // 5. assets/ folder
  const assetsFolder = root.folder('assets');
  if (assetsFolder) {
    assetsFolder.file(
      'info.txt',
      `Assets Directory for ${options.projectName}\nPlace any images or fonts here and reference them as "assets/filename.png".`
    );
  }

  const blob = await zip.generateAsync({
    type: 'blob',
    compression: 'DEFLATE',
    compressionOptions: { level: 9 },
  });

  const filename = `${folderName}.zip`;
  const file = new File([blob], filename, { type: 'application/zip' });

  return { blob, filename, file };
}

/**
 * Triggers instant browser download of the ZIP file
 */
export async function downloadProjectZip(options: ProjectPackageOptions): Promise<File> {
  const { blob, filename, file } = await generateProjectZip(options);
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  setTimeout(() => {
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, 2000);
  return file;
}

/**
 * Attempts to share the file or project via Web Share API
 */
export async function shareProject(
  file: File | null,
  projectName: string,
  learnerName: string
): Promise<'shared' | 'unsupported'> {
  if (typeof navigator !== 'undefined' && navigator.share) {
    try {
      if (file && navigator.canShare && navigator.canShare({ files: [file] })) {
        await navigator.share({
          files: [file],
          title: `My First Web Design: ${projectName}`,
          text: `Check out "${projectName}" created by ${learnerName} on Internet Mission!`,
        });
        return 'shared';
      } else {
        await navigator.share({
          title: `My First Web Design: ${projectName}`,
          text: `I just built "${projectName}" on Internet Mission! Join the community to see web projects: https://chat.whatsapp.com/EVCWh9Vxfk2KLzOdpQMzYJ`,
        });
        return 'shared';
      }
    } catch (err: any) {
      if (err.name === 'AbortError') return 'shared';
      console.warn('Share API error:', err);
    }
  }
  return 'unsupported';
}
